before:
  hooks:
    # - go mod tidy
    # - go generate ./...

builds:
- main: ./cmd/latest/main.go

  env:
  - CGO_ENABLED=0

  goarch:
  - amd64
  - arm64

  goos:
  - linux
  - darwin

  ldflags:
  - -s -w
  - -X github.com/IPA-CyberLab/latest/version.Version={{.Version}}
  - -X github.com/IPA-CyberLab/latest/version.Commit={{.Commit}}
  # - -X main.date={{.Date}} -X main.builtBy=goreleaser

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
- goos: linux
  goarch: amd64
  goarm: ''
  binaries:
  - latest

  image_templates:
  - "ghcr.io/ipa-cyberlab/kmgm-issuer:latest"

  skip_push: false
  dockerfile: Dockerfile
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
